### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('f...

### ISSUE THREAD

**Issue by vanton** [suda/tool-bar#154]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package, v1.0.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.

```
At /Users/vanton1/.atom/packages/tool-bar/lib/tool-bar-button-view.js:36

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at new ToolBarButtonView (/Users/vanton1/.atom/packages/tool-bar/lib/tool-bar-button-view.js:36:31)
    at ToolBarManager.addButton (/Users/vanton1/.atom/packages/tool-bar/lib/tool-bar-manager.js:14:20)
    at Object.utils.addButton (/Users/vanton1/.atom/packages/tool-bar-almighty/lib/utils.coffee:17:11)
    at Object.utils.parseEntry (/Users/vanton1/.atom/packages/tool-bar-almighty/lib/utils.coffee:29:13)
    at Object.toolBarAlmighty.consumeToolBar (/Users/vanton1/.atom/packages/tool-bar-almighty/lib/tool-bar-almighty.coffee:34:11)
    at Provider.module.exports.Provider.provide (/Users/vanton1/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Users/vanton1/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-color-highlight",
      "symbols-view",
      "atom-fecs"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/vanton1/works"
  },
  "tool-bar": {
    "position": "Left"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.0
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-ctags, v4.5.2
atom-ternjs, v0.14.2
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
color-picker, v2.2.2
colorful-json, v1.0.0
docblock-format-helper, v0.3.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.17
highlight-column, v0.5.1
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
js-hyperclick, v1.4.2
json-schema, v0.1.15
language-apache, v1.5.0
language-log, v1.5.0
language-lua, v0.9.4
language-sql-mysql, v0.3.1
language-swift, v0.4.0
linter, v1.11.14
linter-jsonlint, v1.3.0
linter-php, v1.2.0
linter-shellcheck, v1.2.0
merge-conflicts, v1.4.4
minimap, v4.24.7
minimap-color-highlight, v4.1.4
pigments, v0.31.1
project-manager, v2.9.7
simplified-chinese-menu, v3.4.11
symbols-tree-view, v0.13.2
tabs-to-spaces, v1.0.2
tool-bar, v1.0.0
tool-bar-almighty, v0.6.1
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by MuhunKim** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package, v1.0.0


### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.

```
At /C:/Users/Kim/.atom/packages/tool-bar/lib/tool-bar-button-view.js:45

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at new ToolBarButtonView (C:/Users/Kim/.atom/packages/tool-bar/lib/tool-bar-button-view.js:36:31)
    at ToolBarManager.addButton (C:/Users/Kim/.atom/packages/tool-bar/lib/tool-bar-manager.js:14:20)
    at Object.utils.addButton (file:///C:/Users/Kim/.atom/packages/tool-bar-almighty/lib/utils.coffee:17:11)
    at Object.utils.parseEntry (file:///C:/Users/Kim/.atom/packages/tool-bar-almighty/lib/utils.coffee:29:13)
    at Object.toolBarAlmighty.consumeToolBar (file:///C:/Users/Kim/.atom/packages/tool-bar-almighty/lib/tool-bar-almighty.coffee:34:11)
    at Provider.module.exports.Provider.provide (C:\Users\Kim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Kim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "tool-bar": {
    "iconSize": "16px",
    "position": "Left"
  }
}
```

### Installed Packages

```coffee
# User
atom-webbrowser, v2.1.4
chester-atom-syntax, v0.1.1
emmet, v2.4.3
language-svg, v0.9.0
pdf-view, v0.50.0
seti-icons, v1.3.2
svg-preview, v0.8.0
terminal-plus, v0.14.5
tool-bar, v1.0.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by jerone** [comment]
Please read https://github.com/suda/tool-bar/issues/148 as this is an plugin issue from tool-bar-almighty and subscribe to https://github.com/varemenos/atom-toolbar-almighty/issues/17.
