### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by geekerator** [suda/tool-bar#228]
Fix to 1.1.6 didn't work for me...

openSuSE 42.3
Atom:  1.17.2 x64
tool-bar: 1.1.6
UI theme: One Dark

Stack trace:
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/home/jdcook/.atom/packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:1)
    at Object.<anonymous> (/home/jdcook/.atom/packages/tool-bar/lib/tool-bar.js:3:25)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:887:1)
    at /usr/share/atom/resources/app/src/package.js:158:1
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:1)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:562:1)
    at /usr/share/atom/resources/app/src/package-manager.js:476:1
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:321:1)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:470:1)
    at /usr/share/atom/resources/app/src/atom-environment.js:798:1

**Comment by geekerator** [comment]
Thanks to all for the suggestions, but none of them made any difference.
Additional informational displayed under "Failed to load..." message:

cannot match against 'undefined' or 'null'.

**Comment by trycoon** [comment]
I've got the same error now when I just upgraded the touch-bar package.

**Comment by geekerator** [comment]
Voila! I finally just completely uninstalled atom, deleted the .atom 
directory, and reinstalled atom from the ground up. Then I reinstalled 
the all packages I had previously installed. The problem has gone 
away...Jeff

**Comment by trycoon** [comment]
Thanks, I'll try that when I get some sparetime over.
// Henrik

**Comment by dpetican** [comment]
So reinstalling everything is the only solution?

**Comment by geekerator** [comment]
IDK, but it worked for me. I simply got tired of chasing the problem 
(and I had other work to do), so took the quickest approach that might work.

**Comment by buschettu** [comment]
Same problem for me.

**Comment by suda** [comment]
Sorry for a late response. Atom 1.17.2 has been [released 10 months ago](https://github.com/atom/atom/releases/tag/v1.17.2) (current stable is 1.25.0).
I would really recommend upgrading to the latest version. [It definitely solves the problem](https://github.com/suda/tool-bar/issues/214).
