### ISSUE TITLE
Failed to activate the tool-bar package

### ISSUE THREAD

**Issue by cloudbluedigital** [suda/tool-bar#230]
[Enter steps to reproduce:]

1.Go to config
2. Paste this:

```
[
    {
        type: "button"
        icon: "columns"
        iconset: "fa"
        callback: "pane:split-right",
    }
    {
        type: "button"
        iconset: "fa"
        icon: "github"
        callback: "git-plus:menu"
        style: color: "#4286f4"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "plug"
        tooltip: "Make Controller"
        callback: "artisan:make controller"
        style: color: "#f44150"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "legal"
        tooltip: "Make Model"
        callback: "artisan:make model"
        style: color: "#eff241"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "table"
        tooltip: "Make Migration"
        callback: "artisan:make migration"
        style: color: "#efb107"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "filter"
        tooltip: "Make Seeder"
        callback: "artisan:make seeder"
        style: color: "#e041d5"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "coffee"
        tooltip: "Make Test"
        callback: "artisan:make test"
        style: color: "#02843a"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "fighter-jet"
        tooltip: "Make Job"
        callback: "artisan:make job"
        style: color: "#09c9f9"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "user"
        tooltip: "Make Provider"
        callback: "artisan:make provider"
        style: color: "#J2G4D7"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "book"
        tooltip: "Make Command"
        callback: "artisan:make command"
        style: color: "brown"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "paper-plane"
        tooltip: "Make Notification"
        callback: "artisan:make notification"
        style: color: "#06dae2"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "envelope"
        tooltip: "Make Mail"
        callback: "artisan:make mail"
        style: color: "#b2e206"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "paw"
        tooltip: "Make Event"
        callback: "artisan:make event"
        style: color: "#e88504"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "phone"
        tooltip: "Make Listener"
        callback: "artisan:make listener"
        style: color: "#5b62e5"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "flag"
        tooltip: "Make Policy"
        callback: "artisan:make policy"
        style: color: "#6f2fb7"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "rocket"
        tooltip: "Make Rule"
        callback: "artisan:make rule"
        style: color: "#6g3dg0"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "industry"
        tooltip: "Make Factory"
        callback: "artisan:make factory"
        style: color: "black"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "exclamation"
        tooltip: "Make Exception"
        callback: "artisan:make exception"
        style: color: "blue"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "recycle"
        tooltip: "Make Channel"
        callback: "artisan:make channel"
        style: color: "yellow"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "gear"
        tooltip: "Make Resource"
        callback: "artisan:make resource"
        style: color: "orange"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "reply"
        tooltip: "Make Request"
        callback: "artisan:make request"
        style: color: "#c16067"
    }
    {
        type: "button"
        iconset: "fa"
        icon: "trash"
        tooltip: "Cache Clear"
        callback: "artisan:cache clear"
        style: color: "c9f2d6"
    }
    {
        type: "url"
        iconset: "fa"
        icon: "chrome"
        tooltip: "Debugging"
        url: "http://localhost:3000"
        style: color: "#f7f3f0"
    }
]
```

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Kali GNU/Linux
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.7
**User**: root

### Stack Trace

Failed to activate the tool-bar package

```
At Unexpected identifier

SyntaxError: Unexpected identifier
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.loadConfig (/packages/flex-tool-bar/lib/flex-tool-bar.js:590:15)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.js:430:32)
    at Object.consumeToolBar (/packages/flex-tool-bar/lib/flex-tool-bar.js:414:8)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/usr/share/atom/resources/app/src/package.js:397:75)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:233:20)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/usr/share/atom/resources/app/src/config.js:862:28)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:867:27)
    at <anonymous>
```

### Commands

```
     -0:33.7.0 command-palette:toggle (atom-pane.pane)
     -0:29.4.0 core:backspace (input.hidden-input)
     -0:28.7.0 core:confirm (input.hidden-input)
     -0:28.7.0 flex-tool-bar:edit-config-file (atom-pane.pane)
  6x -0:27.1.0 core:move-down (input.hidden-input)
  2x -0:24.6.0 core:move-right (input.hidden-input)
     -0:22.5.0 core:backspace (input.hidden-input)
     -0:22 intentions:highlight (input.hidden-input)
     -0:21.9.0 core:save (input.hidden-input)
     -0:20.3.0 core:backspace (input.hidden-input)
     -0:20.1.0 intentions:highlight (input.hidden-input)
     -0:19.9.0 core:save (input.hidden-input)
undefined -0:18.3.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
artisan 0.3.2 
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
atom-material-ui 2.1.3 
atom-npm-outdated 0.13.2 
autocomplete-module-import 0.3.0 
autocomplete-sql 0.5.0 
autoupdate-packages 1.3.1 
blade-spacer 0.4.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
chester-atom-syntax 0.3.2 
city-lights-syntax 1.1.8 
composer 0.5.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.17 
flex-tool-bar 2.0.0 
git-plus 7.10.2 
ide-cquery 0.8.1 
ide-css 0.2.0 
ide-docker 0.0.2 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.13 
ide-python 0.8.2 
ide-typescript 0.7.6 
ide-vue 0.1.8 
ide-yaml 0.4.2 
intentions 1.1.5 
language-blade 0.38.0 
language-vue 0.23.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
react 0.18.0 
sync-settings 0.8.5 
teletype 0.10.0 
tool-bar 1.1.7 
```

**Comment by UziTech** [comment]
Your config file needs to be a .cson file for that configuration to work
