### ISSUE TITLE
Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 117Error: Cannot cal...

### ISSUE THREAD

**Issue by charles-e** [suda/tool-bar#232]
[Enter steps to reproduce:]
Sorry - no idea what I did to induce this traceback
1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.5
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.7

### Stack Trace

Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 117
Error: Cannot call function 'setTouchBar' on missing remote object 117
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'setTouchBar' on missing remote object 117
Error: Cannot call function 'setTouchBar' on missing remote object 117
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at TouchBarManager._setTouchBar (/packages/tool-bar/lib/touch-bar-manager.js:86:29)
    at _updateDebounce.setTimeout (/packages/tool-bar/lib/touch-bar-manager.js:38:50)
```

### Commands

```
     -0:20.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -0:17.6.0 core:backspace (input.hidden-input)
     -0:11.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
aesthetic-ui 4.0.0 
aligner-python 1.1.0 
angular-2 0.2.6 
angular-auto-import 0.3.5 
angularjs 0.5.3 
atom-diary 1.2.1 
atom-ide-ui 0.11.0 
atom-terminal 0.8.0 
atom-typescript 12.3.8 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
color-picker 2.3.0 
color-tabs 0.1.8 
emmet 2.4.3 
fizzy 0.21.0 
gloom 0.6.5 
Hydrogen 2.4.1 
ide-css 0.3.0 
ide-python 0.9.2 
ide-typescript 0.7.6 
jumpy 4.2.0 
monokai 0.24.0 
organized 0.8.1 
project-colorize 0.3.0 
project-manager 3.3.5 
python-jedi 0.3.8 
python-tools 0.6.9 
seti-syntax 1.1.3 
seti-ui 1.10.0 
tool-bar 1.1.7 
unity-dark-syntax 0.1.4 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
wordpress 0.2.0 
wordpress-api 1.2.2 
yeti-syntax 0.1.2 
Zen 0.18.0 
```

**Comment by suda** [comment]
Oh, that's is interesting. A couple of questions: 
- Does your Mac come with TouchBar?
- Was there an Atom window opened?
- When do you see this error? On Atom start?

**Comment by charles-e** [comment]
This is a shiny new macbook with touchbar.  I use Atom quite a bit and have
not had any weirdness other than this one crash.
Looking right now I notice (for the first time) that there are only two
unlabeled touchbar buttons specific to Atom: one attempts to attach to a
debugger and the opens the atom console.
I am mostly using Atom to edit typescript.  If this crash had to do with
the touchbar I probably hit a button by accident.

That is really all I can add.
