### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by Alex19427** [suda/tool-bar#233]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.4.16 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.7

### Stack Trace

Failed to load the tool-bar package

```
At Cannot match against 'undefined' or 'null'.

TypeError: Cannot match against 'undefined' or 'null'.
    at /packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/tool-bar/lib/tool-bar.js:3:25)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -0:11.5.0 commit-live-welcome:show-dashboard (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
greyatom-ide-background-tips 0.0.3 
greyatom-ide-welcome 0.0.9 
tool-bar 1.1.7 
```

**Comment by suda** [comment]
Hi Alex, Atom 4.4.16 x64 seems to be an odd version considering the latest one is 1.29 now (https://github.com/atom/atom/releases). How did you install it on your system?

**Comment by dkchirag** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.13.6
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package 1.1.4


### Stack Trace

Failed to load the tool-bar package

```
At Cannot match against 'undefined' or 'null'.

TypeError: Cannot match against 'undefined' or 'null'.
    at /packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/tool-bar/lib/tool-bar.js:3:25)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
atom-js-console 1.2.2 
markdown-writer 2.7.5 
tool-bar 1.1.4 
tool-bar-markdown-writer 0.3.1 
typewriter-scroll 1.0.2 
wordcount 3.0.0 
```

**Comment by suda** [comment]
Hi @dkchirag you seem to be using an Atom version released on Apr 12, 2017. I would recommend to the latest one and this problem should go away :)
