### ISSUE TITLE
Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 1Error: Cannot call ...

### ISSUE THREAD

**Issue by Errory** [suda/tool-bar#252]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.1
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.11

### Stack Trace

Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 1
Error: Cannot call function 'setTouchBar' on missing remote object 1
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter. (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents. (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221

Error: Cannot call function 'setTouchBar' on missing remote object 1
Error: Cannot call function 'setTouchBar' on missing remote object 1
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at TouchBarManager._setTouchBar (/packages/tool-bar/lib/touch-bar-manager.js:86:29)
    at _updateDebounce.setTimeout (/packages/tool-bar/lib/touch-bar-manager.js:38:50)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
behave-theme 1.7.0 
build 0.70.0 
build-cmake 0.12.0 
build-dockerfile 1.0.1 
build-tools 4.5.12 
busy-signal 1.4.3 
docker 0.8.0 
file-icons 2.1.26 
gcc-make-run 0.2.12 
git-control 0.9.0 
git-plus 8.1.0 
git-status 0.3.4 
git-time-machine 2.1.0 
go-debug 1.6.2 
go-plus 6.0.2 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
ide-clangd 0.4.0 
ide-cpp 0.0.3 
ide-docker 0.1.0 
intentions 1.1.5 
language-babel 2.85.0 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-docker 1.1.8 
language-graphql 0.11.0 
language-haskell 1.17.8 
language-ignore 1.7.4 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-markdown 0.27.0 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-docker 0.3.2 
linter-gcc 0.7.1 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.10.3 
nucleus-dark-ui 0.12.3 
nuclide 0.366.0 
nuclide-format-js 0.0.47 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
set-syntax 0.4.0 
sort-lines 0.18.0 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by suda** [comment]
@Errory hmm that is unusual. Does it keep happening? What Mac model are you using?
