### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by NJL7502L** [suda/tool-bar#253]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.11

### Stack Trace

Failed to load the tool-bar package

```
At unexpected  in C:\Users\ghana\.atom\packages\tool-bar\keymaps\tool-bar.cson:1:1

SyntaxError: unexpected 
at C:\Users\ghana\.atom\packages\tool-bar\keymaps\tool-bar.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.27 
intentions 1.1.5 
japanese-menu 1.14.0 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
tool-bar 1.1.11 
```

**Comment by suda** [comment]
Can you show the contents of the `C:\Users\ghana\.atom\packages\tool-bar\keymaps\tool-bar.cson` file? Also maybe try to reinstall the package? It looks like it got corrupted somehow

**Comment by cheezemanrich** [comment]
I'm having the same problem under Linux Mint. Tried uninstalling and reinstalling. Started having the problem after updating.

**Here is what the Error shows;**
Cannot match against 'undefined' or 'null'.
Hide Stack Trace
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/home/user/.atom/packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/user/.atom/packages/tool-bar/lib/tool-bar.js:3:25)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:747:27)
    at /usr/share/atom/resources/app.asar/src/package.js:118:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:468:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:407:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:772:28

[tool-bar.cson.txt](https://github.com/suda/tool-bar/files/3203994/tool-bar.cson.txt)
