### ISSUE TITLE
Failed to activate the tool-bar package

### ISSUE THREAD

**Issue by NJL7502L** [suda/tool-bar#254]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.11

### Stack Trace

Failed to activate the tool-bar package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (<embedded>:11:146461)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:145974)
    at /packages/tool-bar/lib/tool-bar-manager.js:2:27)
    at /packages/tool-bar/lib/tool-bar-manager.js:38:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:145974)
    at /packages/tool-bar/lib/tool-bar.js:1:179)
    at /packages/tool-bar/lib/tool-bar.js:56:3)
    at Module.get_Module._compile (<embedded>:11:146684)
    at Object.value [as .js] (<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:1:639369)
    at Package.requireMainModule (<embedded>:11:3041061)
    at Package.activateNow (<embedded>:11:3029195)
    at measure (<embedded>:11:3028973)
    at Package.measure (<embedded>:11:3026604)
    at activationPromise.activationPromise.Promise (<embedded>:11:3028833)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3028776)
    at PackageManager.activatePackage (<embedded>:11:382657)
    at config.transactAsync (<embedded>:11:382273)
    at Config.transactAsync (<embedded>:11:332460)
    at PackageManager.activatePackages (<embedded>:11:382223)
    at PackageManager.activate (<embedded>:11:381841)
    at t.loadState.then (<embedded>:1:660779)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.27 
intentions 1.1.5 
japanese-menu 1.14.0 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
tool-bar 1.1.11 
```

**Comment by suda** [comment]
Hmmm can you try reinstalling the package? Looks like it got corrupted somehow
