### ISSUE TITLE
Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 1414Error: Cannot ca...

### ISSUE THREAD

**Issue by tcheng** [suda/tool-bar#262]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.1.12

### Stack Trace

Uncaught Error: Cannot call function 'setTouchBar' on missing remote object 1414
Error: Cannot call function 'setTouchBar' on missing remote object 1414
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'setTouchBar' on missing remote object 1414
Error: Cannot call function 'setTouchBar' on missing remote object 1414
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at TouchBarManager._setTouchBar (/packages/tool-bar/lib/touch-bar-manager.js:86:29)
    at _updateDebounce.setTimeout (/packages/tool-bar/lib/touch-bar-manager.js:38:50)
```

### Commands

```
     -3:34.7.0 pane:reopen-closed-item (atom-pane.pane.active)
     -3:05.0 core:backspace (input.hidden-input)
     -3:04.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -3:02.7.0 core:move-down (input.hidden-input)
  2x -3:02.3.0 core:move-up (input.hidden-input)
     -3:01.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:00.7.0 editor:newline (input.hidden-input)
     -2:56.5.0 core:copy (input.hidden-input)
     -2:55.2.0 core:paste (input.hidden-input)
     -1:31.8.0 core:copy (input.hidden-input)
  2x -0:55.2.0 core:paste (input.hidden-input)
     -0:43.5.0 core:backspace (input.hidden-input)
     -0:43 core:save (input.hidden-input)
```

### Non-Core Packages

```
ide-json 0.2.1 
markdown-writer 2.11.9 
pretty-json 2.1.2 
tool-bar 1.1.12 
tool-bar-markdown-writer 0.5.0 
```

**Comment by tcheng** [comment]
Actually I'm not sure how to reproduce the error. I just installed the tool bar and made some changes in the markdown file and tried to save the changes. Then the error showed up and asked me to open a ticket.
