### ISSUE TITLE
Failed to activate the tool-bar package

### ISSUE THREAD

**Issue by abdurrhmanFaid** [suda/tool-bar#311]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tool-bar](https://github.com/suda/toolbar) package 1.3.0

### Stack Trace

Failed to activate the tool-bar package

```
At Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.

TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at ToolBarView.addItem (/packages/tool-bar/lib/tool-bar-view.js:82:18)
    at ToolBarManager.addItem (/packages/tool-bar/lib/tool-bar-manager.js:15:22)
    at Object.consumeToolBar (~/github/premio-main-navigation/lib/premio-main-navigation.js:90:18)
    at Provider.provide (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:1060527)
    at ServiceHub.provide (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:3291601)
    at Package.activateServices (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:3299887)
    at Package.activateNow (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:3296863)
    at ~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:383387)
    at ~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:382138
```

**Comment by aminya** [comment]
Which toolbar provider are you using?

**Comment by abdurrhmanFaid** [comment]
> Which toolbar provider are you using?

https://github.com/suda/tool-bar-main

**Comment by suda** [comment]
@abdurrhmanFaid hmm I can't reproduce this. Could you try reinstalling both `tool-bar` and `tool-bar-main`?
