### ISSUE TITLE
Failed to activate the tool-bar package

### ISSUE THREAD

**Issue by codewhisperer97** [suda/tool-bar#85]
[Enter steps to reproduce below:]

1. Copy tool-bar-master folder into ~/.atom/packages/
2. Open atom

**Atom Version**: 1.0.5
**System**: Ubuntu 15.04
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package, v0.1.8

### Stack Trace

Failed to activate the tool-bar package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/nick/.atom/packages/tool-bar-master/lib/tool-bar-view.coffee:9:10)
    at Object.<anonymous> (/home/nick/.atom/packages/tool-bar-master/lib/tool-bar-view.coffee:251:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by jerone** [comment]
You can't _just copy_ a package folder into Atom's package folder. I recommend that you [read the docs](https://atom.io/docs) how to install packages.
