### ISSUE TITLE
Failed to activate the tool-bar package

### ISSUE THREAD

**Issue by urzds** [suda/tool-bar#96]
[Enter steps to reproduce below:]
1. Update tool-bar
2. Get error message

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package, v0.1.10
### Stack Trace

Failed to activate the tool-bar package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at Error (native)
  at ToolBarView.module.exports.ToolBarView.addItem ($HOME/.atom/packages/tool-bar/lib/tool-bar-view.coffee:21:15)
  at ToolBarManager.module.exports.ToolBarManager.addButton ($HOME/.atom/packages/tool-bar/lib/tool-bar-manager.coffee:10:14)
  at Object.consumeToolBar ($HOME/.atom/packages/nuclide-debugger-atom/lib/main.js:230:13)
  at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:330:71)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
  at /usr/share/atom/resources/app.asar/src/package.js:150:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at /usr/share/atom/resources/app.asar/src/package.js:143:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```
### Commands

```
     -4:14.1.0 nuclide-diff-view:open (atom-pane.pane.active)
     -3:50.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter",
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
hyperclick, v0.0.35
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter-clang, v3.3.0
linter-csslint, v1.1.0
linter-gcc, v0.5.11
linter-glsl, v1.0.6
linter-htmlhint, v0.2.2
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-rust, v0.3.0
linter-tidy, v1.0.1
minimap, v4.19.0
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
pdf-view, v0.38.0
project-manager, v2.6.5
tool-bar, v0.1.10
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by suda** [comment]
Hi @urzds this seems to be connected to Nuclide. Could you try to [upgrade it to 0.111.0](http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/) and see if it helps?

**Comment by urzds** [comment]
@suda: Hello! Yes, by now the error message does not appear anymore.

**Comment by suda** [comment]
Great! Thanks for checking this :)

**Comment by stryju** [comment]
0.11.1 didn't help me, tho

---

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package, v0.1.11


### Stack Trace

Failed to activate the tool-bar package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  at Error (native)
  at ToolBarView.module.exports.ToolBarView.addItem (/Users/stryju/.atom/packages/tool-bar/lib/tool-bar-view.coffee:21:15)
  at ToolBarManager.module.exports.ToolBarManager.addButton (/Users/stryju/.atom/packages/tool-bar/lib/tool-bar-manager.coffee:10:14)
  at Object.consumeToolBar (/opt/facebook/nuclide/0.111.20207720-1/nuclide/pkg/nuclide/debugger/atom/lib/main.js:215:13)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:351:71)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:623:20
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:808:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:600:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:12.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "metrics",
      "styleguide",
      "timecop",
      "pane-manager",
      "tree-view"
    ],
    "themes": [
      "atom-material-ui",
      "material-syntax"
    ]
  },
  "tool-bar": {
    "iconSize": "16px",
    "position": "Right"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
docblockr, v0.7.3
emmet, v2.4.0
file-icons, v1.6.14
haskell-grammar, v0.4.0
highlight-selected, v0.11.1
language-babel, v2.11.3
language-ini, v1.14.0
language-ocaml, v1.1.2
language-svg, v0.9.0
language-thrift, v1.0.2
material-syntax, v0.5.0
minimap, v4.19.0
nuclide, v0.111.20207720-1
tool-bar, v0.1.11

# Dev
No dev packages
```

**Comment by jerone** [comment]
Does Nuclide provide two toolbar or alters it standard ToolBar buttons?

**Comment by urzds** [comment]
This is what the tool-bar looks like with Nuclide installed:
![nuclide-tool-bar](https://cloud.githubusercontent.com/assets/15085501/12484287/e01b23bc-c059-11e5-9e1d-33305cde10cc.png)

**Comment by zertosh** [comment]
@jerone I work on nuclide. On both our internal and external releases (for those facebookers reading this) only use one toolbar. However, some features, like the `diff-view` manipulate the toolbar element to show some state. The `diff-view` changes color and shows a badge with the number of changed files. Usually we just mount a React a component on the toolbar element that we cleanup on deactivate.

I have noticed that since the toolbar doesn't provide a mechanism to notify consumers when the `tool-bar` itself is deactivated, we end up in bad state where things like the `diff-view` still think that the toolbar element is in the DOM.

How do you feel about the `ToolBarManager` exposing the `ToolBarView`'s `subscriptions` object (in a sanctioned way), so that consumers can do other cleanup if the `tool-bar` package is disabled? This would really improve the experience of doing a graceful toolbar upgrade for example.

**Comment by jerone** [comment]
You mean that when the Tool Bar package is disabled, the reference to the button added by your package is still alive? 
What about we empty all button references, so when doing changes to your buttons you have to check if your button isn't `null`?

We're always open for an PR.

**Comment by zertosh** [comment]
#101 fixes this issue and provides a way for consumers to be notified when the Tool Bar package is destroyed.

**Comment by jamesgpearce** [comment]
Saw this upgrading to 0.2.0 but I guess I won't see it again?

**Comment by jerone** [comment]
It shouldn't be happening again if you install latest version.

**Comment by newelement** [comment]
This has returned as of Atom v1.16

**Comment by Stanzilla** [comment]
@jerone this is back in Atom 1.16.beta0

`ReferenceError: positionMenu is not defined`

**Comment by danielbayley** [comment]
> this is back in Atom 1.16.beta0

@jerone Me too! 😢

~~~
ReferenceError: positionMenu is not defined
  at ToolBarView.updateMenu (/Users/Dan/Library/Application Support/Atom/packages/tool-bar/lib/tool-bar-view.js:166:39)
  at ToolBarView.updatePosition (/Users/Dan/Library/Application Support/Atom/packages/tool-bar/lib/tool-bar-view.js:155:10)
  at ToolBarView.show (/Users/Dan/Library/Application Support/Atom/packages/tool-bar/lib/tool-bar-view.js:202:10)
  at new ToolBarView (/Users/Dan/Library/Application Support/Atom/packages/tool-bar/lib/tool-bar-view.js:58:12)
  at Object.activate (/Users/Dan/Library/Application Support/Atom/packages/tool-bar/lib/tool-bar.js:25:13)
  at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:218:19)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:96:15)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
  at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:826:28
~~~

**Comment by zertosh** [comment]
#161 fixes the issue in Atom 1.6.0. That's in master already, but @jerone needs to publish a new version.

**Comment by zertosh** [comment]
I just published tool-bar@1.1.0 that fixes the Atom 1.16.0 issue

**Comment by forestgagnon** [comment]
@zertosh the update just broke tool-bar in my Atom 1.15.0

```
TypeError: Cannot read property 'element' of undefined
    at Object.unfixToolBarHeight (/Users/fgagno/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:171:21)
    at Object.reloadToolbar (/Users/fgagno/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:163:8)
    at Object.consumeToolBar (/Users/fgagno/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:151:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:396:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:812:28
```

**Comment by zertosh** [comment]
@forestgagnon looking into it

**Comment by zertosh** [comment]
@forestgagnon here's the fix https://github.com/cakecatz/flex-toolbar/pull/98

**Comment by MggMuggins** [comment]
How do I update to that revision? Will you be pushing a revision that makes sure this doesn't happen in the release versions?

**Comment by cakecatz** [comment]
@forestgagnon I merged @zertosh 's PR and published flex-tool-bar@0.12.0 😎

**Comment by MggMuggins** [comment]
Thanks, works like a charm now!

**Comment by forestgagnon** [comment]
Awesome thanks!
